keys:
  - &rayandrew age1cmp8v76aj2a7vk4re5s9vjdy994t2hcznq76rugzptj9eqda0pesxmpvph
  - &ucare-07 age1xlvqfm5y26k0yths8w3qxe68tm9xj50ccxlua4t6lkuz6wtjcs2s5qyrpj
  - &gitea age1lvprmf420c46gt2z78vegmzn8022y4yzceymyk663vg7d7mtwvrqwry3vf
  - &mail age1wf3g6p346093fz0yuq8u57tvurfw9336evj06ka99uwhrcz9m47qekdkrw
  - &wiki age1v5c8vyxm4u49f9a3mdaqp80n7dnc3w4a5gllggp7cwfu3kp3zazs8s49ky
  - &lemur age14dfjxelzwz6mgr4v5kkula7vce2rlnhyr0r7p48mm6g3sc42kgjqrtsaps
creation_rules:
  - path_regex: secrets.ya?ml$
    key_groups:
      - age:
          - *rayandrew
          - *ucare-07
          - *gitea
          - *mail
          - *wiki
          - *lemur
  - path_regex: hosts/ucare-07/secrets.ya?ml$
    key_groups:
      - age:
          - *rayandrew
          - *ucare-07
          - *lemur
  - path_regex: hosts/gitea/secrets.ya?ml$
    key_groups:
      - age:
          - *rayandrew
          - *gitea
          - *lemur
  - path_regex: hosts/mail/secrets.ya?ml$
    key_groups:
      - age:
          - *rayandrew
          - *mail
          - *lemur
  - path_regex: hosts/wiki/secrets.ya?ml$
    key_groups:
      - age:
          - *rayandrew
          - *wiki
          - *lemur
  - path_regex: hosts/lemur/secrets.ya?ml$
    key_groups:
      - age:
          - *rayandrew
          - *lemur
